name: py35
dependencies:
- pip=8.1.1=py35_0
- python=3.5.1=0
- setuptools=20.3=py35_0
- wheel=0.29.0=py35_0
- pip:
  - agent==0.1.2
  - aiohttp==0.18.2
  - git+https://github.com/felliott/boto.git@feature/gen-url-query-params-6#egg=boto
  - celery==3.1.17
  - cryptography==1.5.2
  - furl==0.4.2
  - humanfriendly==1.31
  - oauthlib==0.7.2
  - pyjwe==1.0.0
  - pyjwt==1.4.0
  - python-dateutil==2.5.3
  - raven==5.27.0
  - stevedore==1.2.0
  - tornado==4.3
  - xmltodict==0.9.0
  - certifi==2015.4.28
